### ISSUE TITLE
Missing the day after

### ISSUE THREAD

**Issue by blappm** [siku2/hass-srf-weather#3]
Hi

There seems to be an off-by-one somewhere, since one full day (the one after the 24 hours listing) is missing:

![grafik](https://user-images.githubusercontent.com/14891555/129458308-9e16300b-ad89-405d-b78c-bb792593ed83.png)

Additional suggestion: It would be great if you could add some average sensor values for the next days:

- SUN_H Sunhours, Temperature, Wind

This would be extremly useful for energy dependent processes (heating during the night or not if the next day is beautiful, etc)

**Comment by kds69** [comment]
solved with proposed PR #10
