### ISSUE TITLE
Wind Bearing

### ISSUE THREAD

**Issue by cyrus4** [siku2/hass-srf-weather#4]
Immer wenn es Windstill ist kommt diese Fehlermeldung und es wird nicht mehr aktualisiert:

Logger: custom_components.srf_weather.weather
Source: custom_components/srf_weather/weather.py:299 
Integration: SRF Weather 
First occurred: 14. Oktober 2021, 19:26:25 (16 occurrences) 
Last logged: 15. Oktober 2021, 21:26:25

failed to update weather
Traceback (most recent call last):
  File "/config/custom_components/srf_weather/weather.py", line 309, in async_update
    await self.__update()
  File "/config/custom_components/srf_weather/weather.py", line 299, in __update
    wind_direction=forecastnow["wind_bearing"],
KeyError: 'wind_bearing'

**Comment by agners** [comment]
Checked my logs, I never saw this. Do you still experience this?

**Comment by siku2** [comment]
No longer relevant with the new version.
