### ISSUE TITLE
Problem with Installation

### ISSUE THREAD

**Issue by hphd70** [siku2/hass-srf-weather#6]
Hi,
It seems that this integration is what I am looking for a long time..

I installed "SRF Weather" in HACS but I cannot add it in the integration:

![image](https://user-images.githubusercontent.com/79278368/147415652-148f185d-5fdd-4d97-930f-c225d561e955.png)

![image](https://user-images.githubusercontent.com/79278368/147415667-a2c3d076-778e-42a1-950a-dcb22d6a8799.png)

what am i doing wrong?
Thanks for your help!

**Comment by siku2** [comment]
The repository was recently renamed and we forgot to adjust the installation instructions. You need to search for "SRF" instead of srg

**Comment by hphd70** [comment]
Thanks! it works now.
is it possible to have the daily forecast only(instead of the houry forecast)?

**Comment by siku2** [comment]
> Thanks! it works now.
> is it possible to have the daily forecast only(instead of the houry forecast)?

The integration doesn't support this currently but it's technically possible. It's not likely that I will implement it myself, but contributions are of course welcome.
See #3
